### ISSUE TITLE
Documentation gone?

### ISSUE THREAD

**Issue by blindpenguin** [WyriHaximus/Ratchet#112]
Hi,

i can't find the documentation. The links in the readme seem to lead to 404 error pages.

**Comment by WyriHaximus** [comment]
Are you looking for the docs for cakephp 2 or 3?

**Comment by blindpenguin** [comment]
The one for 3.

**Comment by WyriHaximus** [comment]
I'll write those tonight, those have been long over due :zipper_mouth_face:

**Comment by blindpenguin** [comment]
No pressure. I was just wondering. 😃

**Comment by WyriHaximus** [comment]
Have to do it anyways so might as well do it now :sunglasses:

**Comment by WyriHaximus** [comment]
Made a start with the new documentation: https://github.com/WyriHaximus/Ratchet/tree/master/docs
