### ISSUE TITLE
Support for WAMP.2 in the CakePHP 2 Plugin?

### ISSUE THREAD

**Issue by TheDuckman** [WyriHaximus/Ratchet#113]
Hey,

I have an application built on CakePHP 2.5.3 and I'm trying to integrate a new VueJs frontend app with it while keeping the rest unchanged. I want the frontend to receive events from the server so I looked around and found your Plugin, got it working on the backend but, since the front is built using JS, the Helper is useless to me.

Since your helper is built using autobahn, I installed it on my VueJs app hoping to simplify things on the client side but I'm getting an error when I try to connect with the server on Chrome (apparently Firefox works just fine because it's less strict when it comes to handshakes).

The error is this:

`WebSocket connection to 'ws://localhost:12345/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

I was able to establish a connection using other (vanilla) websocket libs but I'm interested in the Pub/Sub functionality.

Searching around, I found some info that led me to believe that this error might have something to do with Ratchet not supporting wamp.2.json/wamp.2.msgpack protocols. Can you tell me if thats the case? If so, do you have any idea of how can I fix this?

Thanks!

**Comment by WyriHaximus** [comment]
Right to the version for CakePHP 2 supports wamp v1 through the provided javascript. The version for CakePHP 3 supports wamp v2. IIRC autobahn 0.7 or 0.8 support wamp v1 and they bumped to wamp v2 after that.
