### ISSUE TITLE
I can't start the server

### ISSUE THREAD

**Issue by jannaahs** [WyriHaximus/Ratchet#30]
Hey,
I have a running cakephp website and now i want to add a few pushable stuff for statistics.
I used composer to install Ratchet, RatchetCommands and RatchetModelPush, but i can't start the websocket server.

Here is the displayed error.
```
Welcome to CakePHP v2.5.1 Console
---------------------------------------------------------------
App : app
Path: C:\wamp\www\app\
---------------------------------------------------------------
Your configuration doesn't seem to support 'ext-libevent'. It is highly reccomended that you install and configure it
 as it provides significant performance gains over stream select!
PHP Fatal error:  Declaration of CakeWampAppConnectionTrait::onUnSubscribe($conn, $topic) must be compatible with Rat
chet\Wamp\WampServerInterface::onUnSubscribe(Ratchet\ConnectionInterface $conn, $topic) in C:\wamp\www\app\Plugin\Rat
chet\Lib\Wamp\CakeWampAppServer.php on line 171
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\app\Console\cake.php:0
PHP   2. ShellDispatcher::run() C:\wamp\www\app\Console\cake.php:36
PHP   3. ShellDispatcher->dispatch() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:66
PHP   4. Shell->runCommand() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:207
PHP   5. WebsocketShell->start() C:\wamp\www\lib\Cake\Console\Shell.php:437
PHP   6. App::load() C:\wamp\www\lib\Cake\Console\Shell.php:0
PHP   7. include() C:\wamp\www\lib\Cake\Core\App.php:565

Fatal error: Declaration of CakeWampAppConnectionTrait::onUnSubscribe($conn, $topic) must be compatible with Ratchet\
Wamp\WampServerInterface::onUnSubscribe(Ratchet\ConnectionInterface $conn, $topic) in C:\wamp\www\app\Plugin\Ratchet\
Lib\Wamp\CakeWampAppServer.php on line 171

Call Stack:
    0.0010     124888   1. {main}() C:\wamp\www\app\Console\cake.php:0
    0.0020     187960   2. ShellDispatcher::run() C:\wamp\www\app\Console\cake.php:36
    0.0540    1663768   3. ShellDispatcher->dispatch() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:66
    0.1540    1895800   4. Shell->runCommand() C:\wamp\www\lib\Cake\Console\ShellDispatcher.php:207
    0.2790    2469248   5. WebsocketShell->start() C:\wamp\www\lib\Cake\Console\Shell.php:437
    0.6790    2696896   6. App::load() C:\wamp\www\lib\Cake\Console\Shell.php:0
    0.6950    2717184   7. include('C:\wamp\www\app\Plugin\Ratchet\Lib\Wamp\CakeWampAppServer.php') C:\wamp\www\lib\C
ake\Core\App.php:565

Fatal Error Error: Declaration of CakeWampAppConnectionTrait::onUnSubscribe($conn, $topic) must be compatible with Ra
tchet\Wamp\WampServerInterface::onUnSubscribe(Ratchet\ConnectionInterface $conn, $topic) in [C:\wamp\www\app\Plugin\R
atchet\Lib\Wamp\CakeWampAppServer.php, line 171]
```

Is there a solution or is it a bug?
I didn't understand the structur of all those plugins and libs working together.

Regards
Jan

**Comment by pejonic** [comment]
Please i want to know how to add this amazing plugin to my cakephp 2.x? Thanks
I added this `require_once(APP . 'Config' . DS . 'constants.php');` but not tool sure.

**Comment by WyriHaximus** [comment]
Hey you can find the install instructions for 2.x here: https://github.com/WyriHaximus/Ratchet/tree/cake2#getting-started

**Comment by pejonic** [comment]
Thanks WyriHaximus, Please how can I save to database from Ratchet Server?

**Comment by WyriHaximus** [comment]
Assuming you also want it for cake2, you could utilize https://github.com/WyriHaximus/reactphp-child-process-promise-closure (been using child processes to do the same for cake3 in this package: https://github.com/WyriHaximus/cakephp-async-orm )

**Comment by pejonic** [comment]
Error: Plugin Ratchet could not be found.
#0 C:\SERVER_HOME\www\web_root\lib\Cake\Core\App.php(227): CakePlugin::path('Ratchet')
#1 C:\SERVER_HOME\www\web_root\lib\Cake\Core\App.php(549): App::path('Console/Command', 'Ratchet')
#2 [internal function]: App::load('WebsocketShell')
#3 [internal function]: spl_autoload_call('WebsocketShell')
#4 C:\SERVER_HOME\www\web_root\lib\Cake\Console\ShellDispatcher.php(252): class_exists('WebsocketShell')
#5 C:\SERVER_HOME\www\web_root\lib\Cake\Console\ShellDispatcher.php(203): ShellDispatcher->_getShell('Ratchet.websock...')
#6 C:\SERVER_HOME\www\web_root\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 C:\SERVER_HOME\www\web_root\app\Console\cake.php(24): ShellDispatcher::run(Array)
#8 {main}

`CakePlugin::load('Ratchet' => ['bootstrap' => true]);`
Please sir I have done everything in the document. I got the above error, please what next. Thanks.

**Comment by WyriHaximus** [comment]
Make sure you've read and applied the bit linked to about composer and cake 2. It is essential. Also I haven't touched cake 2 in years and staying far away from it, so no clue beyond those instructions.

**Comment by pejonic** [comment]
OK, I am now using git bash

Error i saw was => Your configuration doesn't seem to support 'ext-libevent'. It is highly reccomended that you install and configure it as it provides significant performance gains over stream select!
[1496092421.7150] Event begin: Rachet.WampServer.construct
Your configuration doesn't seem to support 'ext-pcntl'. It is highly recomended that you install and configure it as it provides OS signaling support!
[1496092421.7158] Event end: Rachet.WampServer.construct

**Comment by WyriHaximus** [comment]
Yeah that is fine during development, those are improvements you can do by installing those extensions. They aren't needed to get started.

**Comment by pejonic** [comment]
Please I will need a little configuration to start it. Thanks Sir

**Comment by pejonic** [comment]
I mean for the server IP address and Port

**Comment by pejonic** [comment]
I did it with this 
`Configure::write('Ratchet.Connection.websocket', [
    'address' => '127.0.0.1', // The IP to listen on
    'port' => 11001, // The port to listen on
]);

Configure::write('Ratchet.Connection.external', [
    'hostname' => 'localhost', // The hostname (or IP) serving the websocket server
    'port' => 80, // The port the websocket server is served over (note that this can be on the same ort as your HTTP server due to proxies like HAproxy or nginx)
    'path' => 'websocket', // Path
    'secure' => false, // Secure connection or not
]);
Configure::write('Ratchet.Connection.keepaliveInterval', 23);

Configure::write('Ratchet.Client', [
	'retryDelay' => 500, // Not the best option but it speeds up development
	'maxRetries' => 500, // Keep on trying! (Also not the best option)
]);`
Thanks! 👍

**Comment by pejonic** [comment]
Sorry sir, I have ask too many questions. please I want to understand how to pass the data from  WebSocket to MySQL server. Like in a Real-time chat app. If I have client A ->(send) data ->(to) B how will the server handle this request and save it to Database? Thanks
