### ISSUE TITLE
WebSocket connection to 'ws://localhost/websocket' failed

### ISSUE THREAD

**Issue by ajfranzoia** [WyriHaximus/Ratchet#31]
Hello. I've started the server successfully from console but after loading page it won't connect to the ws. The error message is "WebSocket connection to 'ws://localhost/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404".

The console task seems to be running normaly, this is the output:

```
[1410805625.7352] Event begin: Rachet.WampServer.construct
[1410805625.7352] Event end: Rachet.WampServer.construct
```

**Comment by Creemli** [comment]
Actually I have also seen this error, and the reason is using Safari to debug.
