### ISSUE TITLE
Can't Install via Composer

### ISSUE THREAD

**Issue by dariusve** [WyriHaximus/Ratchet#35]
During the install process it's asking for a username and password:

 Authentication required (packagist.org):
      Username:
      Password:

  [Composer\Downloader\TransportException]
  Invalid credentials for 'http://packagist.org/p/wyrihaximus/ratchet$97fc49e
  767278f9bc02982b4fd936d52dfbf92c951235006a016606d29e6f6cf.json', aborting.

Any clue?

**Comment by WyriHaximus** [comment]
Packagist doesn't require you to authenticate (ref https://github.com/composer/composer/issues/2574) can you run a `composer diagnose`?

**Comment by dariusve** [comment]
<pre>
satecadm@satecweb:~$ php ~/composer.phar diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking composer version: OK

</pre>

**Comment by WyriHaximus** [comment]
Hmm same as mine 0_o. Have you [tried this](https://github.com/composer/composer/issues/2574#issuecomment-42234160)?

**Comment by dariusve** [comment]
I think it's our squid proxy:

<pre>
satecadm@satecweb:~/websock$ curl -I -L http://packagist.org/p/wyrihaximus/ratchet$97fc49e767278f9bc02982b4fd936d52dfbf92c951235006a016606d29e6f6cf.json
HTTP/1.0 403 Forbidden
Server: squid/2.5.STABLE6
Mime-Version: 1.0
Date: Fri, 06 Feb 2015 20:09:21 GMT
Content-Type: text/html
Content-Length: 1433
Expires: Fri, 06 Feb 2015 20:09:21 GMT
X-Squid-Error: ERR_ACCESS_DENIED 0
X-Cache: MISS from webserver
Connection: close


</pre>

**Comment by WyriHaximus** [comment]
Alright, closing this as it's an issue with composer not this package. Did you manage to fix the squid?
