### ISSUE TITLE
Can't start the server: Missing Class

### ISSUE THREAD

**Issue by dariusve** [WyriHaximus/Ratchet#36]
I got this error when trying to start the Ratchet server:
<pre>
C:\Apache24\htdocs\websock\app>Console\cake Ratchet.websocket start --verbose

Welcome to CakePHP v2.6.1 Console
---------------------------------------------------------------
App : app
Path: C:\Apache24\htdocs\websock\app\
---------------------------------------------------------------

Fatal error: Class 'React\EventLoop\Factory' not found in C:\Apache24\htdocs\web
sock\app\Plugin\Ratchet\Console\Command\WebsocketShell.php on line 51
Fatal Error Error: Class 'React\EventLoop\Factory' not found in [C:\Apache24\htd
ocs\websock\app\Plugin\Ratchet\Console\Command\WebsocketShell.php, line 51]

</pre>

Any clue?

**Comment by dariusve** [comment]
Fixed!

Just missed to add the following lines to my ```Config/bootstrap.php```:
```
require APP . 'Vendor/autoload.php';
spl_autoload_unregister(array('App', 'load'));
spl_autoload_register(array('App', 'load'), true, true);
```

And everything worked fine!

**Comment by dariusve** [comment]
You also need to copy this line in your ```compose.json``` on the ```require``` section
 ```
 "react/zmq": "dev-master"
 ```

**Comment by WyriHaximus** [comment]
:+1: , correct you need to use composers autoloader to get everything loaded. In cake2 that's a pita tbh but already porting it to cake3 where it's a breeze.
