### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by fvelcker** [WyriHaximus/Ratchet#38]
I am quite superbad when I don't have an example to work from.
Could it be possible to have a very simple concrete example on how to use the plugin ?
Something like clicking on a button sends an alert to all connected clients.

Thank you !

**Comment by rifton007** [comment]
Anyone can answer, I have the same problem!

**Comment by WyriHaximus** [comment]
Hey is this about cake2 or cake3? For cake 3, simply connect to the running service using autobahn and send a message over a pubsub channel all listening clients are listening to.

http://autobahn.ws/js/reference.html#subscribe and http://autobahn.ws/js/reference.html#publish

**Comment by rifton007** [comment]
Thank you, WyriHaximus.
For me cakePHP 2.x.

I will start to see the links, I return to you again if I blocked again;-)

**Comment by rifton007** [comment]
Hi WyriHaximus,

I see the Authobahn.js guide.
But I get a series of errors. I do not know if it comes on the server side or client side.

![capture](https://cloud.githubusercontent.com/assets/2601347/12933531/dcae7bdc-cf88-11e5-9fd7-215c2e86ecc5.PNG)

My question, how to debug the server side?
You is it possible to intercept and read send server side?

Dank u ;-)

**Comment by rifton007** [comment]
Apparently this is because of Ratchet, it is not compatible with WAMP v2.

**Comment by rifton007** [comment]
I spent all night on it without success.

`    // WAMP server
    var wsuri = "ws://localhost:1307";

    ab.connect(
        wsuri,

        function (session) {

            cakeWamp.call('Plugin.TopicName', {
                foo: 'bar'
            }).then(function(responseData) {
                console.log(responseData);
            });

        },

        function (code, reason) {
            console.log(reason);
        }
    )`

![capture](https://cloud.githubusercontent.com/assets/2601347/12939146/8711e9f0-cfbc-11e5-9061-a0524f10be8e.PNG)

[WyriHaximus/Ratchet - DOC/Client side](http://wyrihaximus.net/wyri_projects/wyri_project_documents/view/20.html)

> The following code calls the RPC Plugin.TopicName
I did not understand the documentation.
We talk plugin, after the event. I did not understand the transition, do I also create a plugin in addition to the event?

Thank you,

**Comment by WyriHaximus** [comment]
Right  for cake2 there is a client bundled you can use with a compatible version of autobahn: http://wyrihaximus.net/projects/cakephp/ratchet/documentation/client.html and http://wyrihaximus.net/wyri_projects/wyri_project_documents/view/25.html

Cake2 version of this plugin uses WAMPv1 and cake3 uses WAMPv2 which is a completely different protocol and needs a compatible version of autobahn.

**Comment by stablestorage** [comment]
Hi i would appreciate a basic setup and use example for cakephp 3 too :) i saw theres already a tab on the documentation page... any idea when this is ready?

**Comment by WyriHaximus** [comment]
There is no ETA when it will be ready. Currently working on fixing stuff over at [cakephp-async-orm](https://github.com/WyriHaximus/cakephp-async-orm) to work as intended before fixing/figuring out the following things for this plugin:

- Connection open/close events
- Channel creation/joining/leaving events
- Auth
- Docs for all the above

The basics are working, can send events to channels and between clients but not everything from the cake2 plugin is in yet. Will look into updating the readme with a working example later this week. Rehashing my site somewhere this year, also needing this plugin for it :wink:

**Comment by stablestorage** [comment]
hi i dont want to pressure but are there news regarding a simple example and the cake3 integration process? kind regards

**Comment by WyriHaximus** [comment]
@stablestorage yes I've made great progress over the past week or two. Figured out how you can stop any event from continuing or not, that needs documentation. And currently changing the way you register services with the router. Keep an eye on this branch: https://github.com/WyriHaximus/Ratchet/tree/thruway-0.4 will also ping here when things are updated.
