### ISSUE TITLE
Question about session integration

### ISSUE THREAD

**Issue by rhelms** [WyriHaximus/Ratchet#39]
I see you have some provisioning for sessions in this plugin.

What assumptions and expectations should there be for session integration with this plugin?

For example, the Ratchet documentation is pretty clear that it uses Symfony sessions, however, if a user is using this plugin, they might expect it to work with CakePHP sessions?

Could it be expected to support CakePHP sessions that are stored in the database, rather than cache or local disk? If not, are there locations where an implementation could be passed to allow the plugin to read sessions from the database?

**Comment by WyriHaximus** [comment]
For the CakePHP2.0 version of this plugin no new features or support will be added. It should be fairly easy to add support for by extending the websocket shell and overruling the `setUpRatchet` method. Another option would be to wrap a cache handler around session reading.
