### ISSUE TITLE
 Could not bind to tcp://:: Failed to parse address ":"

### ISSUE THREAD

**Issue by tmholloway** [WyriHaximus/Ratchet#40]
I've had the exact same issues as WisdomProductionz from this issue https://github.com/WyriHaximus/Ratchet/issues/37 , but now I'm stuck. When I run "./Console/cake Ratchet.websocket start --verbose" I get the following error

    Welcome to CakePHP v2.3.8 Console
    ---------------------------------------------------------------
    App : app
    Path: /Applications/XAMPP/xamppfiles/htdocs/app/
    ---------------------------------------------------------------
    Your configuration doesn't seem to support 'ext-libevent'. It is highly reccomended that you install and configure it as it provides significant performance gains over stream select!
    Error: Could not bind to tcp://:: Failed to parse address ":"
    #0 /Applications/XAMPP/xamppfiles/htdocs/app/Plugin/Ratchet/Console/Command/WebsocketShell.php(63): React\Socket\Server->listen(NULL, NULL)
    #1 /Applications/XAMPP/xamppfiles/htdocs/lib/Cake/Console/Shell.php(389): WebsocketShell->start()
    #2 /Applications/XAMPP/xamppfiles/htdocs/lib/Cake/Console/ShellDispatcher.php(200): Shell->runCommand('start', Array)
    #3 /Applications/XAMPP/xamppfiles/htdocs/lib/Cake/Console/ShellDispatcher.php(68): ShellDispatcher->dispatch()
    #4 /Applications/XAMPP/xamppfiles/htdocs/app/Console/cake.php(37): ShellDispatcher::run(Array)
    #5 {main}

I tried debugging like you previous suggested but got the exact same results as WisdomProductionz

In /app/Config/boostraph.php I have
   
    CakePlugin::loadAll();
    require APP . '/Vendor/autoload.php';

My bootstrap located in /app/Plugin/Ratchet/Config/bootstrap.php is complete unmodified. No includes or modifications were made.

I made sure zmq is installed. When I run the following in a php file I made it displays "4.1.3", so I know that is in fact working

    if (class_exists("ZMQ") && defined("ZMQ::LIBZMQ_VER")) {
        echo ZMQ::LIBZMQ_VER, PHP_EOL;
    }

What else would case the "could not bind..." error?

**Comment by WyriHaximus** [comment]
The `could not bind` error is cause because it can't find any IP and port information. What configuration do you use for the plugin?

**Comment by tmholloway** [comment]
Thanks for the quick reply. Now that you mention it, I'm pretty sure my ratchet bootstrap file isn't even being loaded. It is however, untouched (the default settings).  In my /app/Config/bootstrap.php I have

    CakePlugin::loadAll();

which I assumed would load all the plugins. I opened up my ratchet boostrap file from /app/Plugin/Ratchet/Config/bootstrap.php and tried changing a few things but I still got the "could not bind" error. I added some invalid characters that would throw a PHP error (just to check if the file was loaded), but those weren't caught. I cleared my persistent cache directory and had the same results.

I then went back to my /app/Config/bootstrap.php file and added another line, so it is 

    CakePlugin::loadAll();
    CakePlugin::load('Ratchet', ['bootstrap' => true]);

And now I get the following error

    [1441379167.2187] Event begin: Rachet.WampServer.construct

    Fatal error: Class 'MKraemer\ReactPCNTL\PCNTL' not found in /Applications/XAMPP/xamppfiles/htdocs/app/Plugin/Ratchet/Event/PcntlListener.php on line 39


My /app/Plugin directory has the following contents

    Ratchet
    RatchetCommands
    RatchetModelPush

**Comment by WyriHaximus** [comment]
Good to hear your issue is resolved.

The helper generates the javascript code needed, but it's just a autobahnjs 0.7 client with some handy helpers. Something like this:

```html
<script type="text/javascript">
//<![CDATA[
WEB_SOCKET_SWF_LOCATION = "http://example.com/Ratchet/swf/WebSocketMain.swf";
var cakeWamp = window.cakeWamp || {};
cakeWamp.options = {retryDelay: 5000,maxRetries: 25};
var wsuri = "ws://example.com:80/websocket";
//]]>
</script><script type="text/javascript" src="/js/cache/Ratchet.wamp.js"></script><script type="text/javascript">
//<![CDATA[
cakeWamp.subscribe('Rachet.connection.keepAlive', function (topic, event) {});
//]]>
</script>
```

Judging by the `Rachet.WampServer.onOpen` the connecting is working. If you have debug mode enabled you should see the messages between the client and server.

**Comment by tmholloway** [comment]
Thanks again for your help. I have a question but didn't want to open another issue because it's in regards to functionality rather than an issue/bug. I sent an email, but figured I'd respond here  too just in case it gets caught by your spam filter.

I'm trying to keep track of users connected to the websocket at any given time. Upon a new connection (or subscribe), how can I receive the connection session id from the CakeEvent object? I tried to use something like debug($event), but I clumsily realized that it just loops over and over, so I wasn't able to retrieve any sort of indication. For that matter, is the session_id even available from a CakeEvent object?

For example

    //in an EvenTListener
    public function implementedEvents(){
        return array(
           'Rachet.WampServer.onSubscribe.testSubscribe' => 'register_user_connection',
         );
    }

    public function register_user_connection(CakeEvent $event){
        $session_id = $event->data->somethingOrOther->session_id; //is the session data available from the $event object?
    }

I realize that I can just retrieve it from the onconnectListeners on the client side, then call an RPC and send the session_id, but I was hoping there's a less "hacky" way of doing it. It would also be quite useful to retrieve the session_id when a user unsubscribes so that I can remove that user from an array of active connections that I have on the server.

Thanks
