### ISSUE TITLE
Websocket connection timeout

### ISSUE THREAD

**Issue by tmholloway** [WyriHaximus/Ratchet#41]
From the terminal, the websocket starts up and appears to run fine. This is what I see

    [1441849230.0383] Event begin: Rachet.WampServer.construct
    [1441849230.0392] Event end: Rachet.WampServer.construct

When I open my browser and go to a page that uses the websocket, I get a connection timeout

    WebSocket connection to 'ws://my.ip.address:8080/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

I created [this post](http://serverfault.com/questions/721343/apache-port-8080-not-listening) on serverfault.com with a lot of detail of the situation, but as of now I'm not sure what to do. 

Here is my Ratchet config

    Configure::write('Ratchet', [
        'Client' => [
            'retryDelay' => 5000, // Not the best option but it speeds up development
            'maxRetries' => 25, // Keep on trying! (Also not the best option)
        ],
        'Connection' => [
            'websocket' => [
                'address' => '0.0.0.0',
                'port' => 8080,
            ],
            'external' => [
                'hostname' => 'my.ip.address',
                'port' => 8080,
                'path' => 'websocket',
                'secure' => false,
            ],
            'keepaliveInterval' => 23, // Why 23? Because NGINX kills after 30 seconds, set to 0 to disable
        ],
    ]);

I would greatly appreciate any suggestions.

Thanks

Edit - Well, it was stupid of me, but my EC2 security group wasn't configured properly. For anyone reading this having connectivity issues, if you use EC2 make sure to enable port 8080 (or whatever port you use).

**Comment by WyriHaximus** [comment]
Good to hear it's fixed. If you want to go over part 80 together with the rest of the site take a look at nginx or varnish. The external config setting lets you set the public port which can be routed to the websocket port by varnish or nginx.
