### ISSUE TITLE
Spelling inconsistencies

### ISSUE THREAD

**Issue by tmholloway** [WyriHaximus/Ratchet#42]
I had some trouble getting an RPC to trigger and I realized it was because I spelled it 'Ratchet' (which the plugin is named) rather than 'Rachet' (which is used throughout the documentation), such as on [this page](http://wyrihaximus.net/wyri_projects/wyri_project_documents/view/20.html). 

In the documentation it shows the following for the server-side code for an RPC

```
public function implementedEvents() {
        return array(
            'Rachet.WampServer.Rpc.search' => 'search', //should it be 'Ratchet' rather than 'Rachet'?
        );
   }
```

The following is in /App/Plugin/Ratchet/Lib/Wamp/CakeWampAppRpcTrait.php

```
$event = $this->dispatchEvent(
                'Rachet.WampServer.Rpc', //should it be 'Ratchet.WampServer.Rpc' ?
            $this,
            array_merge($eventPayload, [
                'topicName' => $topicName,
                'topic' => $topic,
                'params' => $params,
                'wampServer' => $this,
            ])
        );
```

I apologize if you have a specific reason for this. If not, I'll gladly make all the changes, test it, and then issue a pull request. However, that would mean you'd have to update your documentation too! 

I apologize if someone has brought this to your attention.

**Comment by WyriHaximus** [comment]
You're absolutely right this is a major typo. I'm currently working on the cake3 version in the master branch but I'll create a cake2 branch you can fork and make a PR with all the fixes in to (documentation is in the docs folder). Currently without internet so sorry for the long response time

**Comment by WyriHaximus** [comment]
Branch `cake2` created :)
