### ISSUE TITLE
Current built assets incompatible?

### ISSUE THREAD

**Issue by jeremyharris** [WyriHaximus/Ratchet#45]
When using the master branch's built assets, I'm getting the following error:

```
WebSocket connection to 'ws://<my_host>:8080/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

I looked into it and it may be related to this issue, https://github.com/crossbario/autobahn-js/issues/100, basically Ratchet's WAMP needs an older version of autobahn to work. What version is the plugin currently using?

**Comment by WyriHaximus** [comment]
Correct, I'm in the process of rethinking those as well, and part of that is figuring out. Using this in my js right now. Thinking out how to make that in a simple asset to use:
```js
//var WAMP_FEATURES = {};
import autobahn from 'autobahn';

var connection = new autobahn.Connection({
    url: 'ws://192.168.1.181:9000/',
    realm: 'first'
});

connection.open();

module.exports = connection;
```
