### ISSUE TITLE
Stable for CakePHP3

### ISSUE THREAD

**Issue by TheMiller2015** [WyriHaximus/Ratchet#46]
Hello @WyriHaximus ! Thanks for your work on this cake-plugin! I want to use it in a production environment of cakephp3. Is your plugin fully compatible with cake3?

Thanks!

**Comment by WyriHaximus** [comment]
Hey @TheMiller2015, it is fully compatible with cake3, just not done. Als the documentation isn't up to date. Been busy with is the past few months getting it up to shape and the core (sending messages back and forth between clients) is working, the model push plugin is working. But I'm not 100% sure about the emitted events, IIRC they work but aren't documented yet.

**Comment by TheMiller2015** [comment]
Thanks. So If I understand you correctly, it's safer to wait using it. Implementing Ratchet not as a plugin is not that problem. Came up with a Server (loop), a class for PubSub and a class for sending messages, so that sending just need `$pusher->send("general", "hello world");` when the AppController instantiates the Pusher-Class with `$pusher = new Pusher;` The rest is done by javascript and anything else. So implementing your plugin lateron is possible and not much work, isn't it?

**Comment by WyriHaximus** [comment]
My plugin is purely for getting things from **a** to **b** and **c**. So it you separate everything switching over should be easy. Also authobahn is used on the client side, something you can read up on before switching.

**Comment by JayPHP** [comment]
Hey @WyriHaximus, 

Any news on the full Cake v3 compatibility?

**Comment by WyriHaximus** [comment]
@JayPHP it is 'compatible' with cake v3. Just make sure you install `dev-master` for now. The main thing I still have to figure out some auth related questions. Right now everyone can hook onto every channel.

**Comment by JayPHP** [comment]
@WyriHaximus ah, that's great - I'll give it a go tomorrow. Thanks for this plugin :)

**Comment by JayPHP** [comment]
@WyriHaximus Doesn't seem to be working up to now, but will keep trying.

**Comment by thanhlong203** [comment]
I'm really thankful for your nice library, but the link for your document is no longer available. Please public it again, i cant found a better one. Thanks so much

**Comment by Mark-Lister** [comment]
Are there any examples for this available on v3 I'm not sure where to start after installing. Or any recommendations on what I should read? Thanks.

**Comment by WyriHaximus** [comment]
@Mark-Lister I'll answer that in #138
