### ISSUE TITLE
cake2 branch, how to access connected clients info from eventlistener

### ISSUE THREAD

**Issue by IvanCaceres** [WyriHaximus/Ratchet#48]
Hello, my question seems like it may be straight forward but i can't find the correct index/object on the CakeEvent instance.

I have an onPublish callback like so:

``` php
public function newMsg(CakeEvent $cakeEvent) {

        var_dump("new msg!!!");

        $cakeEvent->subject()->broadcast('movement.chat', [

            'newMsg' => $cakeEvent->data['event']['msg'],

        ]);

    }
```

I want to broadcast back the new message to every client connected on the channel except for the issuer? How would i go about doing this? I'm thinking it should be something similar to the below when you're only using plain Ratchet without the WyriHaximus plugin.

Here's a simple plain ratchet example of what i'm trying to accomplish:

``` php
public function onMessage(ConnectionInterface $from, $msg) {
    //send the message to all the other clients except the one who sent.
    foreach ($this->clients as $client) {
        if ($from !== $client) {
            $client->send($msg);
        }
    }
}
```

Is there any way to grab the clients / client info from the CakeEventListener?

**Comment by WyriHaximus** [comment]
Well when you do a broadcast on a topic it gets broadcasted to all the listening clients by default, including the sender IIRC. No need for you to keep track of that, but if you want listen for the onSubscribe event: https://github.com/WyriHaximus/Ratchet/blob/cake2/docs/events.md#pubsub
