### ISSUE TITLE
Is the plugin compatible with cakephp 3.3.0?

### ISSUE THREAD

**Issue by WaseemAR** [WyriHaximus/Ratchet#50]
Hi,
I tried installing the plugin via composer and i get the following error:
- Installing ←[32mwyrihaximus/ratchet←[39m (←[33m0.1.0←[39m)
  Loading from cache

symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
wyrihaximus/ratchet suggests installing mkraemer/react-pcntl (Add support for OS signaling)
←[30;43mPackage guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.←[39;49m
←[30;43mPackage guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.←[39;49m
←[30;43mPackage guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.←[39;49m
←[30;43mPackage guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.←[39;49m
←[32mWriting lock file←[39m
←[32mGenerating autoload files←[39m

> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> ←[37;41mScript Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the post-autoload-dump event terminated with an exception←[39;49m

←[37;41mInstallation failed, reverting ./composer.json to its original content.←[39;49m

←[37;41m                                                                                                                                              ←[39;49m
←[37;41m  [RuntimeException]                                                                                                                          ←[39;49m
←[37;41m  Unable to get primary namespace for package wyrihaximus/ratchet.                                                                            ←[39;49m
←[37;41m  Ensure you have added proper 'autoload' section to your plugin's config as stated in README on https://github.com/cakephp/plugin-installer  ←[39;49m
←[37;41m                                                                                                                                              ←[39;49m

←[32mrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [←[39m←[32m<packages>←[39m←[32m]...←[39m

This error seems to be because its not compatible with the current cake version.!

**Comment by WyriHaximus** [comment]
For cake 3 install dev-master instead of 0.1.0, also [I'm working on docs for 3.0 support](https://github.com/WyriHaximus/Ratchet/issues/38#issuecomment-252728465)
