### ISSUE TITLE
Cake php 3.6 Support

### ISSUE THREAD

**Issue by RatzSumit** [WyriHaximus/Ratchet#55]
Is this plugin compatible with cake php 3.6.0 ?

**Comment by WyriHaximus** [comment]
Yes, admittedly I should merge my main dev branch with master which contains all the latest changes.

**Comment by WyriHaximus** [comment]
Done so in #56, will update docs and tag a release for cakephp 3 somewhere next week

**Comment by RatzSumit** [comment]
Thanks for quick reply.  Can i use this combination for multiplayer game.

1. Cake Php 3.6
2. Ratchet socket
3. Curl
4.. MySql

Shall i look for any better alternative ? or this will be fine for execution ?

**Comment by WyriHaximus** [comment]
Well 1 and 2 are covered. For 3 I recommend using https://github.com/clue/reactphp-buzz and for 4 you have two options a) use https://github.com/friends-of-reactphp/mysql to write your own SQL queries or b) use https://github.com/wyrihaximus/cakephp-async-orm which lets you use CakePHP's tables (also needs more documentation)
